---
all:
  hosts:
    desktop:
      ansible_connection: ssh
      ansible_host: vagrant_desktop
    laptop:
      ansible_connection: ssh
      ansible_host: vagrant_laptop
    ubuntu_control: # Control to test if my roles work on Ubuntu 22.04
      ansible_connection: ssh
      ansible_host: vagrant_ubuntu_control
  children:
    fedora:
      hosts:
        desktop:
        laptop:
    ubuntu:
      hosts:
        ubuntu_control: # Control to test if my roles work on Ubuntu 22.04
