---
discord_user: "{{ global_user }}"
discord_version: discord
discord_install_betterdiscord: true
discord_betterdiscord_plugins:
  - "https://mwittrien.github.io/BetterDiscordAddons/Library/0BDFDB.plugin.js"
  - "https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/master/Plugins/BetterRoleColors/BetterRoleColors.plugin.js"

discord_betterdiscord_themes:
  - url: https://betterdiscord.app/Download?id=124
    name: HorizontalServerList
