---
- name: Place autologin config
  become: true
  ansible.builtin.template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart SDDM

- meta: flush_handlers
